-- lua/neogit/keys.lua
vim.keymap.set("n", "<leader>gs", "<cmd>Neogit<CR>", { desc = "Git status" })
vim.keymap.set("n", "<leader>gc", "<cmd>Neogit commit<CR>", { desc = "Git commit" })
vim.keymap.set("n", "<leader>gl", "<cmd>Neogit log<CR>", { desc = "Git log" })
vim.keymap.set("n", "<leader>gp", function()
  _G.NeogitSafePush()
end, { desc = "Git push (safe)" })
vim.keymap.set("n", "<leader>gP", function()
  _G.NeogitSafePushForce()
end, { desc = "Git force push (safe)" })
vim.keymap.set("n", "<leader>gL", "<cmd>Neogit pull<CR>", { desc = "Git pull" })
vim.keymap.set("n", "<leader>gC", "<cmd>Neogit checkout<CR>", { desc = "Git checkout" })
vim.keymap.set("n", "<leader>gm", "<cmd>Neogit branch<CR>", { desc = "Git branch" })
vim.keymap.set("n", "<leader>gF", "<cmd>Neogit fetch<CR>", { desc = "Git fetch" })
vim.keymap.set("n", "<leader>gM", "<cmd>Neogit merge<CR>", { desc = "Git merge" })
vim.keymap.set("n", "<leader>gr", "<cmd>Neogit rebase<CR>", { desc = "Git rebase" })
vim.keymap.set("n", "<leader>gd", "<cmd>Neogit diff<CR>", { desc = "Git diff" })
