-- Java compile/run is handled by the shared terminal runner mapped to
-- <leader>tr (\tr), defined in nvim/lua/terminal/keys.lua. It auto-detects
-- Maven (mvnw/pom.xml) and Gradle (gradlew/build.gradle[.kts]) projects and
-- falls back to javac/java for a single file.
