# PATH

# Root of LinuxSetup ZSH config (resolved dynamically, no hardcoded path)
ZSH_ROOT="${${(%):-%x}:A:h}"

export PATH="$ZSH_ROOT/bin:$PATH"

source "$ZSH_ROOT/config.zsh"

# History
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000
SAVEHIST=10000

setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt SHARE_HISTORY
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

# Load core files
source "$ZSH_ROOT/core/prompt.zsh"
source "$ZSH_ROOT/core/aliases.zsh"
source "$ZSH_ROOT/core/command-not-found.zsh"
source "$ZSH_ROOT/core/plugins.zsh"
export PATH="$HOME/.local/bin:$PATH"

bwuser () {
  bw get item "$1" | jq -r '.login.username'
}

bwpass() {
    bw get item "$1" --session "$BW_SESSION" \
        | jq -r '.login.password' \
        | wl-copy
    echo "Password copied"
}

bwunlock() {
    export BW_SESSION=$(NODE_NO_WARNINGS=1 bw unlock --raw )
}
